# Generated by Django 4.2.27 on 2025-12-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportmetric',
            name='api_reportm_tenant__a28fb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportmetric',
            name='api_reportm_tenant__1bbda1_idx',
        ),
        migrations.RemoveField(
            model_name='reportmetric',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='reportmetric',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.store'),
        ),
        migrations.AddIndex(
            model_name='reportmetric',
            index=models.Index(fields=['store', 'report_type', 'report_date'], name='api_reportm_store_i_739f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmetric',
            index=models.Index(fields=['store', 'report_date', 'metric_name'], name='api_reportm_store_i_1d8a00_idx'),
        ),
    ]
