# Generated by Django 4.2.27 on 2025-12-23 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populate_store_location_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField()),
                ('revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labor_target_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'week_start_date'], name='api_storeta_store_i_571242_idx')],
                'unique_together': {('store', 'week_start_date')},
            },
        ),
    ]
