# Generated by Django 4.2.27 on 2025-12-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_store_daily_targets_and_unique_store_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storetarget',
            new_name='api_storeta_store_i_985653_idx',
            old_name='api_storeta_store_i_target_idx',
        ),
    ]
