# Generated by Django 4.2.27 on 2025-12-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tenant_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
    ]
