# Generated by Django 4.2.27 on 2025-12-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'Franchisee', 'verbose_name_plural': 'Franchisees'},
        ),
    ]
