# Generated by Django 4.2.27 on 2026-01-04 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreport',
            name='report_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('production', 'Production'), ('sales-accrual', 'Sales Accrual')], max_length=50),
        ),
        migrations.CreateModel(
            name='LPAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_ratio_yellow_min', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('cash_ratio_red_min', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('tip_percent_green_min', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('tip_percent_green_max', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('tip_percent_yellow_low', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('tip_percent_yellow_high', models.DecimalField(decimal_places=2, default=35.0, max_digits=5)),
                ('low_ticket_yellow_min', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('low_ticket_red_min', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lp_config', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='LPRiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('cash_ratio_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_ratio_risk', models.CharField(default='low', max_length=20)),
                ('cash_ratio_points', models.IntegerField(default=0)),
                ('tip_percent_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tip_percent_risk', models.CharField(default='low', max_length=20)),
                ('tip_percent_points', models.IntegerField(default=0)),
                ('low_ticket_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('low_ticket_risk', models.CharField(default='low', max_length=20)),
                ('low_ticket_points', models.IntegerField(default=0)),
                ('base_points', models.IntegerField(default=0)),
                ('pattern_bonus', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cc_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('service_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_services', models.IntegerField(default=0)),
                ('low_ticket_services', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lp_risk_scores', to='api.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store', 'report_date'], name='api_lprisks_store_i_197bb8_idx'), models.Index(fields=['total_score'], name='api_lprisks_total_s_326373_idx'), models.Index(fields=['report_date'], name='api_lprisks_report__796bcd_idx')],
                'unique_together': {('store', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='LPAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('cash_ratio', 'High Cash to Credit Ratio'), ('tip_percent', 'Abnormal Tip Percentage'), ('low_ticket', 'High % of Low-Ticket Services')], max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('calculated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('threshold_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('threshold_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('report_date', models.DateField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lp_alerts', to='api.store')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['store', 'alert_type', 'report_date'], name='api_lpalert_store_i_48a3bd_idx'), models.Index(fields=['status'], name='api_lpalert_status_fe290e_idx'), models.Index(fields=['risk_level'], name='api_lpalert_risk_le_d684aa_idx'), models.Index(fields=['detected_at'], name='api_lpalert_detecte_345217_idx')],
            },
        ),
        migrations.CreateModel(
            name='LowTicketService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='low_ticket_services', to='api.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'service_name')},
            },
        ),
    ]
