# Generated by Django 4.2.27 on 2026-01-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_rawreport_report_type_lpalertconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpalertconfig',
            name='pattern_bonus_2_flagged',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='lpalertconfig',
            name='pattern_bonus_2_red',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='lpalertconfig',
            name='pattern_bonus_2_yellow',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='lpalertconfig',
            name='risk_points_high',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='lpalertconfig',
            name='risk_points_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lpalertconfig',
            name='risk_points_medium',
            field=models.IntegerField(default=15),
        ),
    ]
