# Generated by Django 4.2.27 on 2026-02-10 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_lpalertconfig_pattern_bonus_2_flagged_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application Configuration',
                'db_table': 'app_config',
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Sales Flash'), ('weekly', 'Weekly Sales Summary'), ('lp', 'LP Risk Analysis')], max_length=20)),
                ('schedule_time', models.TimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('recipients', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, max_length=20, null=True)),
                ('last_run_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to='api.tenant')),
            ],
            options={
                'db_table': 'report_schedules',
                'indexes': [models.Index(fields=['tenant'], name='rs_tenant_idx'), models.Index(fields=['is_active'], name='rs_active_idx'), models.Index(fields=['schedule_time'], name='rs_time_idx')],
            },
        ),
    ]
