# Generated by Django 4.2.28 on 2026-02-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_populate_cron_and_report_types_remove_old_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExponentialCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_bucket', models.CharField(choices=[('4wk', '4-Week (Low Churn Risk)'), ('6wk', '6-Week (Medium Churn Risk)'), ('8wk', '8-Week (High Churn Risk)')], max_length=10)),
                ('message_template', models.TextField()),
                ('coupon_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('scope', models.CharField(choices=[('all', 'All Locations'), ('single', 'Single Location')], default='all', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_delivered', models.IntegerField(default=0)),
                ('messages_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_campaigns', to='api.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_campaigns', to='api.tenant')),
            ],
            options={
                'db_table': 'exp_campaigns',
            },
        ),
        migrations.CreateModel(
            name='ExponentialCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_code', models.CharField(max_length=100)),
                ('guest_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_opt_in', models.BooleanField(default=False)),
                ('total_visits', models.IntegerField(default=0)),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('previous_visit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_customers', to='api.store')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_customers', to='api.tenant')),
            ],
            options={
                'db_table': 'exp_customers',
            },
        ),
        migrations.CreateModel(
            name='ExponentialSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_at_send', models.CharField(max_length=10)),
                ('coupon_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('message_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('twilio_message_sid', models.CharField(blank=True, help_text='Twilio message SID', max_length=64, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='api.exponentialcampaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='api.exponentialcustomer')),
            ],
            options={
                'db_table': 'exp_sms_logs',
            },
        ),
        migrations.CreateModel(
            name='ExponentialUptake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_visit_date', models.DateField()),
                ('days_to_return', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptakes', to='api.exponentialcustomer')),
                ('sms_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uptake', to='api.exponentialsmslog')),
            ],
            options={
                'db_table': 'exp_uptakes',
            },
        ),
        migrations.CreateModel(
            name='ExponentialSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('4wk', '4-Week (Low Churn Risk)'), ('6wk', '6-Week (Medium Churn Risk)'), ('8wk', '8-Week (High Churn Risk)')], max_length=10)),
                ('days_since_last_visit', models.IntegerField(default=0)),
                ('visits_last_30_days', models.IntegerField(default=0)),
                ('assigned_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.exponentialcustomer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_segments', to='api.store')),
            ],
            options={
                'db_table': 'exp_segments',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(help_text='Unique slug identifier e.g. 4wk_default', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('bucket', models.CharField(choices=[('4wk', '4-Week (Low Churn Risk)'), ('6wk', '6-Week (Medium Churn Risk)'), ('8wk', '8-Week (High Churn Risk)')], max_length=10)),
                ('body', models.TextField(help_text='Template body. Placeholders: {guest_name}, {store_name}, {coupon_value}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='api.tenant')),
            ],
            options={
                'db_table': 'sms_templates',
                'indexes': [models.Index(fields=['tenant', 'bucket', 'is_active'], name='sms_tpl_tenant_bucket_idx')],
                'unique_together': {('tenant', 'template_id')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingTimeBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_bucket', models.CharField(choices=[('9AM-12PM', '9AM-12PM'), ('12PM-2PM', '12PM-2PM'), ('2PM-5PM', '2PM-5PM'), ('5PM-9PM', '5PM-9PM')], max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('guest_tickets', models.IntegerField(default=0)),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('scheduled_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('avg_payroll_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_idle', models.BooleanField(default=False)),
                ('work_center', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sched_time_buckets', to='api.store')),
            ],
            options={
                'db_table': 'sched_time_buckets',
                'indexes': [models.Index(fields=['store', 'date'], name='sched_tb_store_date_idx'), models.Index(fields=['time_bucket'], name='sched_tb_bucket_idx'), models.Index(fields=['is_idle'], name='sched_tb_idle_idx')],
                'unique_together': {('store', 'date', 'time_bucket', 'work_center')},
            },
        ),
        migrations.CreateModel(
            name='SchedulingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recommendation_type', models.CharField(choices=[('reduce_idle', 'Reduce Idle Coverage'), ('improve_peak', 'Improve Peak Coverage'), ('overtime_control', 'Overtime Control'), ('time_insight', 'Time-of-Day Insight')], max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('metric_value', models.CharField(blank=True, max_length=100)),
                ('time_bucket', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sched_recommendations', to='api.store')),
            ],
            options={
                'db_table': 'sched_recommendations',
                'indexes': [models.Index(fields=['store', 'date'], name='sched_rec_store_date_idx'), models.Index(fields=['recommendation_type'], name='sched_rec_type_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchedulingDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payroll_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_scheduled_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('idle_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_guest_tickets', models.IntegerField(default=0)),
                ('avg_payroll_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('srph', models.DecimalField(decimal_places=2, default=0, help_text='Sales Revenue Per Hour', max_digits=10)),
                ('tplh', models.DecimalField(decimal_places=2, default=0, help_text='Tickets Per Labor Hour', max_digits=8)),
                ('pct_idle', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('has_overtime', models.BooleanField(default=False)),
                ('scheduling_quality_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sched_daily_metrics', to='api.store')),
            ],
            options={
                'db_table': 'sched_daily_metrics',
                'indexes': [models.Index(fields=['store', 'date'], name='sched_dm_store_date_idx'), models.Index(fields=['pct_idle'], name='sched_dm_pct_idle_idx')],
                'unique_together': {('store', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ExponentialVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('center_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.exponentialcustomer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_visits', to='api.store')),
            ],
            options={
                'db_table': 'exp_visits',
                'indexes': [models.Index(fields=['customer', 'visit_date'], name='exp_visit_cust_date_idx'), models.Index(fields=['store', 'visit_date'], name='exp_visit_store_date_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='exponentialsmslog',
            index=models.Index(fields=['campaign', 'status'], name='exp_sms_camp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exponentialsmslog',
            index=models.Index(fields=['customer', 'sent_at'], name='exp_sms_cust_sent_idx'),
        ),
        migrations.AddIndex(
            model_name='exponentialsegment',
            index=models.Index(fields=['bucket'], name='exp_seg_bucket_idx'),
        ),
        migrations.AddIndex(
            model_name='exponentialsegment',
            index=models.Index(fields=['store', 'bucket'], name='exp_seg_store_bucket_idx'),
        ),
        migrations.AddIndex(
            model_name='exponentialcustomer',
            index=models.Index(fields=['tenant', 'store'], name='exp_cust_tenant_store_idx'),
        ),
        migrations.AddIndex(
            model_name='exponentialcustomer',
            index=models.Index(fields=['last_visit_date'], name='exp_cust_last_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='exponentialcustomer',
            index=models.Index(fields=['sms_opt_in'], name='exp_cust_sms_opt_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exponentialcustomer',
            unique_together={('tenant', 'guest_code')},
        ),
        migrations.AddIndex(
            model_name='exponentialcampaign',
            index=models.Index(fields=['tenant', 'status'], name='exp_camp_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='exponentialcampaign',
            index=models.Index(fields=['target_bucket'], name='exp_camp_bucket_idx'),
        ),
    ]
