# Generated by Django 4.2.28 on 2026-02-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_exponentialcampaign_exponentialcustomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawreport',
            name='report_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('production', 'Production'), ('sales-accrual', 'Sales Accrual'), ('attendance', 'Attendance'), ('business-kpi', 'Business KPI'), ('performance-by-hour', 'Performance By Hour'), ('statutory-pay', 'Statutory Pay')], max_length=50),
        ),
    ]
