# Generated by Django 4.2.28 on 2026-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_rawreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
