# Generated by Django 4.2.28 on 2026-02-25 14:08

from django.db import migrations


REPORT_TYPE_LABELS = {
    'daily': 'Daily Sales',
    'weekly': 'Weekly Sales',
    'lp': 'LP Risk',
}


def populate_names(apps, schema_editor):
    ReportSchedule = apps.get_model('api', 'ReportSchedule')
    used_names = set()
    for schedule in ReportSchedule.objects.all().order_by('id'):
        if schedule.name:
            used_names.add(schedule.name)
            continue
        # Build a descriptive name from report types
        types = schedule.report_types or []
        label_parts = [REPORT_TYPE_LABELS.get(t, t) for t in types[:2]]
        base = ' + '.join(label_parts) if label_parts else 'Report'
        name = f"{base} Schedule"
        # Ensure uniqueness by appending a counter
        candidate = name
        counter = 2
        while candidate in used_names:
            candidate = f"{name} {counter}"
            counter += 1
        schedule.name = candidate
        schedule.save(update_fields=['name'])
        used_names.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_name_to_reportschedule'),
    ]

    operations = [
        migrations.RunPython(populate_names, migrations.RunPython.noop),
    ]
