# Generated by Django 4.2.27 on 2026-03-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_schedulingdailymetrics_checkin_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingtimebucket',
            name='idle_hours_detail',
            field=models.JSONField(blank=True, default=dict, help_text='Per-hour idle flags keyed by 24h int, e.g. {"9": true, "10": false}'),
        ),
    ]
