# Generated by Django 4.2.29 on 2026-03-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_twilio_callback_log_and_guest_opt_outs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliocallbacklog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
