# Generated by Django 4.2.30 on 2026-04-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_store_display_name_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exponentialcampaign',
            name='target_bucket',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exponentialcampaign',
            name='template_variables',
            field=models.JSONField(blank=True, default=dict, help_text='User-supplied template variable values, e.g. {"coupon_value":"20","coupon_code":"SAVE20"}'),
        ),
        migrations.AlterField(
            model_name='exponentialsmslog',
            name='segment_at_send',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rawreport',
            name='report_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('production', 'Production'), ('sales-accrual', 'Sales Accrual'), ('attendance', 'Attendance'), ('business-kpi', 'Business KPI'), ('performance-by-hour', 'Performance By Hour'), ('statutory-pay', 'Statutory Pay'), ('appointments', 'Appointments'), ('guest-opt-outs', 'Guest Opt-outs'), ('manage-guests', 'Manage Guests'), ('sms-opt-in', 'SMS Opt-In')], max_length=50),
        ),
    ]
