# Generated by Django 4.2.30 on 2026-04-08 19:11

from django.db import migrations, models


def backfill_last_service(apps, schema_editor):
    """One-time backfill of last_service from SALES_ACCURAL raw reports."""
    RawReport = apps.get_model('api', 'RawReport')
    ExponentialCustomer = apps.get_model('api', 'ExponentialCustomer')

    # Build guest_code -> Item Name map (newest report first)
    service_map = {}
    for raw in RawReport.objects.filter(
        report_type__in=['sales-accrual', 'SALES_ACCURAL'],
    ).order_by('-report_date'):
        if not isinstance(raw.raw_data, list):
            continue
        for row in raw.raw_data:
            if not isinstance(row, dict):
                continue
            gc = row.get('Guest Code')
            if gc and gc not in service_map and row.get('Item Type') == 'Service' and row.get('Item Name'):
                service_map[gc] = row['Item Name']

    if not service_map:
        return

    # Bulk update in batches
    batch_size = 500
    customers = ExponentialCustomer.objects.filter(
        guest_code__in=list(service_map.keys())
    ).only('id', 'guest_code', 'last_service')

    batch = []
    for c in customers.iterator(chunk_size=batch_size):
        svc = service_map.get(c.guest_code, '')
        if svc and c.last_service != svc:
            c.last_service = svc
            batch.append(c)
            if len(batch) >= batch_size:
                ExponentialCustomer.objects.bulk_update(batch, ['last_service'])
                batch = []

    if batch:
        ExponentialCustomer.objects.bulk_update(batch, ['last_service'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_increase_segment_field_lengths'),
    ]

    operations = [
        migrations.AddField(
            model_name='exponentialcustomer',
            name='last_service',
            field=models.CharField(blank=True, default='', help_text='Last service type from sales-accrual data', max_length=255),
        ),
        migrations.RunPython(backfill_last_service, migrations.RunPython.noop),
    ]
