# Generated by Django 4.2.30 on 2026-04-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_add_service_filter_to_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='booking_link',
            field=models.URLField(blank=True, default='', help_text='Booking link URL for SMS messages', max_length=500),
        ),
    ]
