# Generated by Django 4.2.30 on 2026-04-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_campaign_visit_date_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exponentialcampaign',
            name='service_filter',
            field=models.CharField(blank=True, default='', help_text='Filter eligible customers by last_service (comma-separated for OR)', max_length=255),
        ),
    ]
